spring:
  pid.file: timber.pid
  application:
    name: timber
  servlet:
    multipart:
      enabled: true
      maxFileSize: 100MB
      maxRequestSize: 500MB

  #  base-url: http://127.0.0.1:8080

  main:
    #    allow-circular-references: true
    allow-bean-definition-overriding: true

  mvc:
    hiddenmethod.filter.enabled: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name:
    jdbc-url:
    username:
    password:
    #    connectionProperties: useUnicode=true;characterEncoding=utf-8;
    #    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    connectionTimeout: 60000
    minimumIdle: 10
    maximumPoolSize: 300
    maxLifetime: 175000
    autoReconnect: true
    validationQuery: select 1
    leakDetectionThreshold: 60000
    hikari:
      leak-detection-threshold: 60000

  sql:
    init:
      platform:
      schema:
      data:
      mode:

  jpa:
    open-in-view: false
    format_sql: true
    show-sql: false
    generate-ddl: false
    defer-datasource-initialization: true
    hibernate:
      jdbc.batch_size: 100
      order_updates: true
      #      order_inserts: true
      ddl-auto:  #create create-drop, update, validate, none
      #      use-new-id-generator-mappings: false
      cache:
        use_second_level_cache: false
        use_query_cache: false
        use_sql_comments: false
      temp:
        use_jdbc_metadata_defaults: false
    properties:
      hibernate.cache:
        use_second_level_cache: false
        use_query_cache: false
      javax.persistence.sharedcache.mode: ENABLE_SELECTIVE

  aop:
    proxy-target-class: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  cache:
    type: NONE

  redis:
    #    timeout: 5000
    cluster.nodes:
    host:
    port:
    password:

  data:
    rest.basePath: /api

  quartz:
    scheduler-name: QuartzScheduler
    batchTriggerAcquisitionMaxCount: 20
    idleWaitTime: 1000
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    #    jdbc.schema: classpath:/quartz/quartz-ddl-mssql.sql
    #    jdbc.schema: classpath:quartz/quartz-ddl-mysql.sql
    overwrite-existing-jobs: true
    scheduler:
      instanceName: QuartzScheduler
      instanceId: AUTO
      skipUpdateCheck: true
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadNamePrefix: QuartzScheduler
      threadCount: 25
      threadPriority: 5
    jobStore:
      useProperties: true
      tablePrefix: QRTZ_
      isClustered: true
      #        class: org.quartz.impl.jdbcjobstore.JobStoreTX
      class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
      clusterCheckinInterval: 5000
      acquireTriggersWithinLock: true
      txIsolationLevelSerializable: true
      misfireThreshold: 60000
      lockHandler:
        class: org.quartz.impl.jdbcjobstore.StdRowLockSemaphore
    properties.org.quartz.jobStore:
      useProperties: true
      tablePrefix: QRTZ_
      isClustered: true
      #      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
      clusterCheckinInterval: 5000
      acquireTriggersWithinLock: true
      txIsolationLevelSerializable: true
      misfireThreshold: 60000
      lockHandler:
        class: org.quartz.impl.jdbcjobstore.StdRowLockSemaphore

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        debug: false
        transport.protocol: smtps
        store.protocol: pop3
        smtp:
          #          ssl.enable: true
          auth: true
          starttls.enable: true
          connecttimeout: 30000
          timeout: 30000
          writetimeout: 30000

  thymeleaf:
    enabled: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    check-template-location: true
    order: 0
    cache: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration


java.net.preferIPv4Stack: true

server:
  port: 8080
  connection-timeout: 30000
  tomcat.connection-timeout: 30000
  jetty.idle-timeout: 30000
  servlet.context-path: /
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048
  error:
    #    whitelabel.enabled: true
    #    include-exception: false
    #    include-stacktrace: never
    path: /error
  ssl:
    enabled: false
#    protocol: TLS
#    enabled-protocols: TLSv1.2
#    key-store-type: PKCS12
#    key-store: classpath:keystore/keystore.p12
#    key-store-password:

#logback:
#  configurationFile: classpath:log/logback-spring.xml

logging:
  config: classpath:logback-spring.xml
#  level:
#    root: INFO
#    org.thymeleaf: OFF
#    io.lettuce: OFF
#    log4jdbc.log4j2: OFF
#    org:
#      hibernate:
#        SQL: DEBUG
#        type.descriptor.sql.BasicBinder: DEBUG
#      springframework.jdbc.core:
#        JdbcTemplate: DEBUG
#        StatementCreatorUtils: DEBUG

#    com.zaxxer.hikari: DEBUG

#mybatis:
#  type-aliases-package: xyz.needpainkiller.**.dao
#  mapper-locations: /mapper/**/*.xml

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
  metrics:
    export.prometheus.enabled: true
    cache.instrument: true
  endpoint:
    prometheus.enabled: true
    metric.enabled: true

jasypt:
  encryptor:
    bean: stringEncryptor

api:
  path-pattern: /api/**
  path-pattern-v1: /api/v1/**
  path-pattern-v2: /api/v2/**
  path-prefix: /api/
  path-prefix-v1: /api/v1/
  path-prefix-v2: /api/v2/

file:
  scope: internal
  path: /files/
  size-usable-limit: 1073741824 # 1GB
  size-upload-limit: 52428800 # 50MB
  extension-restrict: exe,sh,js,ps1,bat,jsp,html,htm,php,cer,asp,pki,war,jar
  delete-expired-file-limit: 7 # 7일
  cipher-secret-key:

resource:
  # internal : classpath 참조
  # external : 외부 경로 참조
  scope: internal
  path: static

jwt:
  secret-key:
  expire-time-ms: 2592000000

#rpa-manager:
#  solution: AA
#  baseUrl:
#  userName:
#  password:

bootstrap:
  enabled: true
  url: http://localhost:8080
  default:
    tenant-name: default
    user-name: admin
    password: qwer1234!
    role-name: ROLE_ADMIN
    team-name: ADMIN_GROUP


rpa:
  system-user: 1
  # RPA 과제 엄격 모드 (과제 스크립트 유효성 체크)
  # true : 엄격 모드 (운영 시 권장)
  # false : 비엄격 모드 (테스트 모드에서만 사용할 것)
  strict-task: true
  # RPA Agent (Bot) 엄격 모드 (Agent API KEY 유효성 체크)
  strict-agent: true
  # 스케줄링 엄격 모드
  #  # true : 엄격 모드 (U Bot 만 스케줄링 가능, CR 에 스케줄링 위임 및 동기화)
  #  # false : 비엄격 모드 (U Bot & A Bot 스케줄링 가능, CR 동기화 비활성화)
  strict-schedule: true

  notification:
    petition: true
    failure: false

  agent.apikey-regen: false
  role.active: false

springfox.documentation.enabled: false

statistics:
  start-epoch-day: 18293 #  20200101

version: '2.0.0-20221214'


springdoc:
  version: '@project.version@'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true
  swagger-ui:
    enabled: true
    show-actuator: true
    path: /index.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    operations-sorter: method
    tags-sorter: alpha
    groups-order: DESC
  paths-to-match:
    - /api/**

sso:
  tenantPk:
  rolePk:
  redirectUrl:
  api:
    cookie:
    #    https://x.y.z:9999
    url:
    header:
      authorization:
        #    None / Bearer / Basic
        type:
        key: